Implement Pose2d PathFollower and PathSequence
Mineinjava/quail pull request #13
Opened 2023-11-30 18:24 UTC by Astr0clad

There are lots of breaking changes - original paths will no longer work.

Translational PID needs to be added for the bot to be stable enough, having better control of speed would also be nice, as the current implementation lets the bot rip it at Mach 10.

Resolves #8 

Docs will be pushed after this gets checked.

2023-11-30 19:18 UTC, Mineinjava requested changes

2023-11-30 19:18 UTC, Mineinjava commented on quail/src/main/java/com/mineinjava/quail/pathing/Path.java
> + * The robot will go to [0,0], then [1,0], then [1,1], then [0,1] always facing '0')
You don't need a closing parenthesis here

2023-11-30 19:18 UTC, Mineinjava commented on quail/src/main/java/com/mineinjava/quail/pathing/Path.java
> +     * @param points - a list of points that the robot will follow (list of Pose2d in order)
Shouldn't this read "list of Pose2d positions..."

2023-11-30 19:18 UTC, Mineinjava commented on quail/src/main/java/com/mineinjava/quail/pathing/Path.java
> +    public int currentPoint = 0;
Change this to currentPointIndex as well as the line below to avoid confusion

2023-11-30 19:18 UTC, Mineinjava commented on quail/src/main/java/com/mineinjava/quail/pathing/PathFollower.java
>          turnSpeed /= this.path.length();
You need to change this to be turnspeed/distance to next point. This is a remnant from when rotation was done over the entire path and not between points.

2023-11-30 19:18 UTC, Mineinjava commented on quail/src/main/java/com/mineinjava/quail/pathing/PathFollower.java
> +        }
I feel like this should be thrown earlier before the user checks if the path is finished.

2023-11-30 19:18 UTC, Mineinjava commented on quail/src/main/java/com/mineinjava/quail/pathing/PathSequenceFollower.java
> +    private long lastTime = System.nanoTime();
Not sure if this will work on all systems.

2023-11-30 19:18 UTC, Mineinjava commented on quail/src/main/java/com/mineinjava/quail/pathing/PathSequenceFollower.java
> +public class PathSequenceFollower {
All of the methods in this class need docstrings.

2023-11-30 23:41 UTC, Mineinjava requested changes

2023-11-30 23:41 UTC, Mineinjava commented on quail/src/main/java/com/mineinjava/quail/pathing/Path.java
>      public int lastpoint = 0;
make this lastPointIndex as well

2023-11-30 23:41 UTC, Mineinjava commented on quail/src/main/java/com/mineinjava/quail/pathing/Path.java
> +    public Pose2d getCurrentPointIndex() {
this shouldn't be `getCurrentPointIndex` as it returns a pose2d object and not an integer

2023-11-30 23:41 UTC, Mineinjava commented on quail/src/main/java/com/mineinjava/quail/pathing/Path.java
> +    public double distanceToNextPoint(Pose2d point){
what if the next point is undefined? (last point in list)

2023-12-04 04:44 UTC, Astr0clad commented
Waiting on #14 before merging this

2023-12-31 00:01 UTC, Mineinjava commented
Need to make path sequences work now

2024-01-01 07:02 UTC, Mineinjava reviewed
Incomplete review. merge when path sequence works

2024-01-01 07:05 UTC, Mineinjava commented
@hhilal123 this is the one that is important
second priority is 3xdeadwheel localizer

2024-01-23 23:51 UTC, Astr0clad commented
Superceded by #20

2024-01-23 23:51 UTC, closed without merging