Added Deadband to MiniPID class
Mineinjava/quail pull request #25
Opened 2024-01-25 19:44 UTC by 2141Robotics

Added deadband to MiniPID class to make steering smoother and to allow for error and stick drift.

2024-01-25 19:55 UTC, Astr0clad requested changes
Resolve fix, test, then it lgtm

2024-01-25 19:55 UTC, Astr0clad commented on quail/src/main/java/com/mineinjava/quail/util/geometry/AccelerationLimitedVector.java
This file needs to be removed from this PR, it is being PRed in #24

2024-01-26 06:19 UTC, Mineinjava commented on quail/src/main/java/com/mineinjava/quail/util/geometry/AccelerationLimitedVector.java
fix by deleting #24

2024-01-26 19:30 UTC, Mineinjava commented
tested--working

2024-01-26 19:32 UTC, Mineinjava commented
fixes #22

2024-01-26 19:33 UTC, merged