fix kalman filter
Mineinjava/quail pull request #40
Opened 2024-02-16 02:10 UTC by 2141Robotics

2024-02-16 02:26 UTC, Mineinjava commented
Appears to work. Will merge when confidence is higher

2024-02-17 03:40 UTC, Mineinjava requested changes
Looks good, just remove the print

2024-02-17 03:40 UTC, Mineinjava commented on quail/src/main/java/com/mineinjava/quail/localization/KalmanFilterLocalizer.java
> +        "k "
Remove print

2024-02-17 20:25 UTC, Bernstern commented
Instead of removing the print I'd add maybe a debug flag to the constructor or some static constant shared across quail for verbose logging 🤷 

I'd also move the `w` param to the constructor since I'm assuming it won't change between calls.

2024-02-17 22:24 UTC, Mineinjava commented
> maybe a debug flag to the constructor or some static constant shared across quail for verbose logging 🤷

This should probably be done properly with logging or some sort of making variables gettable for smart dashboard

2024-02-17 22:25 UTC, Mineinjava commented
> I'd also move the w param to the constructor since I'm assuming it won't change between calls.

W will change between calls as vision noise increases with distance and other variables

2024-02-18 19:53 UTC, Mineinjava approved these changes

2024-02-18 19:53 UTC, merged